# Generated by Django 4.2.20 on 2025-03-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='challenge',
            field=models.FloatField(default=42.2),
        ),
    ]
